### ISSUE TITLE
Basic UI improvements checklist

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/card#9]
- [x] Change receive to request
- [x] Tell users that their gas is held in the browser address on deposit
- [x] Extra confirmation on burning wallet: "Are you SURE?"
- [x] Explicitly show RPC (rinkeby, localhost, mainnet) somewhere on the card
- [x] Scanning a payment request link from within the SendCard QR scanner inputs the whole URL, it should instead just input address (and fill out amount)
- [x] Rename mnemonic to "backup phrase"
- [x] Clear placeholder text when inputting
- [x] App is currently slightly larger than screen which is annoying

**Comment by bohendo** [comment]
Snackbar is currently grey & blends in w the grey background. This should stand out a little, maybe make it Connext orange w black text?
